services:
  redis:
    image: redis:latest
    container_name: bus_hsl_redis
    ports:
      - "6379:6379"
    networks:
      - bus_hsl_net

  app:
    build: .
    container_name: bus_hsl_app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    command: python app.py
    networks:
      - bus_hsl_net

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    env_file:
      - ./.env
    command: python worker.py
    networks:
      - bus_hsl_net

  ingestion:
    build: .
    container_name: bus_hsl_ingestion
    environment:
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    env_file:
      - ./.env
    command: python ingestion.py
    networks:               
      - bus_hsl_net

  spark-lab:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: bus_hsl_spark_lab
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/work/credentials.json
    volumes:
      - .:/home/jovyan/work 
    networks:
      - bus_hsl_net
    depends_on:
      - redis
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Mã cụm giả lập (Bắt buộc phải có cho chế độ KRaft)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      # Trả về đúng địa chỉ kafka:9092 để Python và PySpark của bạn gọi được
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - bus_hsl_net

networks:
  bus_hsl_net:
    driver: bridge